### ISSUE TITLE
Clarification on build process

### ISSUE THREAD

**Issue by 1highmax** [lge-ros2/cloisim#139]
Hello, 
I found this gazebo replacement just recently and I see great potential in it.

However, I did not succeed in building cloisim myself following this [guide](https://github.com/lge-ros2/cloisim/wiki/Build-Guide), but this may be due to the fact that I am a novice in unity.

I proceeded as following:
- installed vulcan and other dependencies as described in guide
- installed unity 2020.3.13f1
- cloned cloisim, cloisim_ros and cloi_common_interfaces
- cloned sample_resources into cloisim
- built and sourced the ros packages
- opened unity
- added the cloisim folder to projects  
![image](https://user-images.githubusercontent.com/21125030/124484136-634bf300-ddab-11eb-925d-2dcda1944025.png)
- opened the project by clicking on it
- did NOT receive a popup about TMP imports, so I importet TMP like [this](https://docs.unity3d.com/Packages/com.unity.textmeshpro@1.3/manual/index.html)
- get a blank window in unity, which results in a blank application when built
![image](https://user-images.githubusercontent.com/21125030/124484572-dd7c7780-ddab-11eb-970f-4426957f2a07.png)

My directory structure is the following:
```
├── cloi_common_interfaces
│   ├── build
│   ├── install
│   ├── log
│   └── src
├── cloisim
│   ├── Assets
│   ├── Docker
│   ├── Library
│   ├── Logs
│   ├── Packages
│   ├── ProjectSettings
│   ├── sample_resources
│   ├── Temp
│   └── UserSettings
├── cloisim_ros
│   ├── build
│   ├── install
│   ├── log
│   └── src
```
I expected to see the shopping hall and a robot.  
Any idea where I am going wrong?  
How is the development workflow like, for instance if I want to use custom maps and robots?  

Thanks in advance and best regards,

Max

**Comment by hyunseok-yang** [comment]
@drdelayismysenpai Hi! sorry for late response. I just realized there was question on issues :(

I will give your answer ASAP.

BTW, are you develop on windows or linux?

**Comment by hyunseok-yang** [comment]
@drdelayismysenpai  

First, I recommend to deploy each directory structure like below. [guid](https://docs.ros.org/en/foxy/Tutorials/Workspace/Creating-A-Workspace.html)

`cloi_ws` is ros2 packages so

|-- cloi_ws/src/cloisim_ros
|-- cloi_ws/src/cloi_common_interfaces
|-- cloi_ws/build/
|-- cloi_ws/install
|
|-- cloisim
|-- sample_resource

**Comment by hyunseok-yang** [comment]
@drdelayismysenpai 
Could you follow the build guide line again?
I revised the guideline in Wiki :)
[link](https://github.com/lge-ros2/cloisim/wiki/Build-Guide)

**Comment by JetBelson** [comment]
> @drdelayismysenpai
> Could you follow the build guide line again?
> I revised the guideline in Wiki :)
> [link](https://github.com/lge-ros2/cloisim/wiki/Build-Guide)

Adding some information about how to set up the Core object (e.g. model directory) in the unity editor will be helpful for beginners.

It is a fantastic project. Great work! Thank you!

**Comment by hyunseok-yang** [comment]
> > @drdelayismysenpai
> > Could you follow the build guide line again?
> > I revised the guideline in Wiki :)
> > [link](https://github.com/lge-ros2/cloisim/wiki/Build-Guide)
> 
> Adding some information about how to set up the Core object (e.g. model directory) in the unity editor will be helpful for beginners.
> 
> It is a fantastic project. Great work! Thank you!

Thanks for comment. i will update the quick guide on Wiki
