### ISSUE TITLE
[Question] How can I make the cloi navigate over the seocho world?

### ISSUE THREAD

**Issue by moran991231** [lge-ros2/cloisim#219]
A clear and concise description of what is your question.
I've done to run the `cloisim` in a docker container and display the `lg_seocho.world`(and other worlds too), and to run the `cloisim_ros` in another docker container, but the cloi has never moved.  
I manipulated it with `teleop_twist_keyboard` but still don't know how to apply your project like README demos.
I'm working on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/55349869/181434103-6848d31a-bf34-47d7-8ae7-4b594f54055e.png)
My poor cloi is standing alone on the freezing lg seocho world.

Please gimme some advice to let cloi run freely!

**Comment by hyunseok-yang** [comment]
Sorry for late response.

`cloisim_ros` is just converter tool between cloisim <-> ros2.

`cloisim_ros` only helps to create a ros2 topic for control or reading sensor data.

Therefore, you need to bringup navigation engine separately.

**Comment by moran991231** [comment]
Thanks for your reply.
I wanna continue this issue here: [https://github.com/lge-ros2/cloisim_ros/issues/55](https://github.com/lge-ros2/cloisim_ros/issues/55)
