### ISSUE TITLE
A quick start example 

### ISSUE THREAD

**Issue by misook3** [lge-ros2/cloisim#32]
I downloaded the sample-resource and the simple-device. Could you explain steps after <After run 'CLOiSim'> of Usage to run any simple example? I fail to locate any launch files to run ROS.

**Comment by zikprid0** [comment]
You can move robot with teleop twist keyboard. with

ros2 run teleop_twist_keyboard teleop_twist_keyboard /cmd_vel:=/cloi/cmd_vel

You need '/cloi' namespace for all topic because we assign namespace each robot.

If you need run navigation2 or cartographor, you need remmapings each topic.

**Comment by hyunseok-yang** [comment]
@misook3 
You need to prepare below packages like you mentioned.
1. CLOiSim
2. [sample-resources](https://github.com/lge-ros2/sample-resources)
3. [sim-device](https://github.com/lge-ros2/sim-device/tree/dashing)

You'd better to launch below script after install ROS2(Dashing) and build sim-device.

Here's a guide. [Usage](https://github.com/lge-ros2/cloisim/wiki/Usage)
1. Do setup ROS2 environment like always
$ . /opt/ros/dashing/setup.bash

2. Set environment variable with the location of resources where you downloaded
export CLOISIM_MODEL_PATH="/home/Unity/cloisim/sample-resources/models"
export CLOISIM_WORLD_PATH="/home/Unity/cloisim/sample-resources/worlds"

3. Do setup sim-device package after build(colcon build).
(it's an one of example, please change the path where you extracted.)
$ ros2 launch simdevice_bringup cloisim_world.launch.py sim_path:=/home/yg/CLOiSimRelease/CLOiSim-1.7.0 world:=lg_seocho.world

refer to this launcher script [here](https://github.com/lge-ros2/sim-device/blob/dashing/bringup/launch/cloisim_world.launch.py)


BTW, 'sim-device' stands for 'simulation-device' :).

**Comment by misook3** [comment]
Thank you very much for your inputs. ^^
However I have an error message about launch file format.
How should I go about this?
![ros2_error_01](https://user-images.githubusercontent.com/67088693/94210877-f695f500-ff0a-11ea-92fc-8eff775d01e1.jpg)

**Comment by misook3** [comment]
Thank you very much for your inputs.
However I have a problem about launch file format.
How should I go about this?
![ros2_error_02](https://user-images.githubusercontent.com/67088693/94211603-d6673580-ff0c-11ea-8379-6245e5182023.jpg)

**Comment by misook3** [comment]
I solved this problem D:
At sim-device-dashing, source install/setup.bash did it.
However, my screen does not show any models and worlds...
What did I miss?
![ros2_error_03](https://user-images.githubusercontent.com/67088693/94214578-e125c880-ff14-11ea-9120-74a88dfb7fea.jpg)

**Comment by hyunseok-yang** [comment]
It looks CLOiSim has been terminated when you launched.
Are you running those simulation on Docker Container? or Remote environment?

If it so, you need to set configuration for X11-display and nvidia driver setting.

**Comment by misook3** [comment]
Ah, I did not run CLOiSim...
After I added another path into an environment, export CLOISIM_FILES_PATH="/home/ubuntu/sample-resources-0.2.0", I ran CLOiSim, but I could not figure it out where I have to change the path...
Did I add a right path?

![ros2_error_05](https://user-images.githubusercontent.com/67088693/94227496-97010f00-ff35-11ea-85f9-2ed5d5e1bc35.jpg)

**Comment by hyunseok-yang** [comment]
Actually "cloisim_world.launch.py" script runs CLOiSim.  That's why it needs to add a **sim_path** as an argument on command.

All you need is just run cloisim_world.launch.py after set ENVIRONMENT variable like below.

ex)
export CLOISIM_WORLD_PATH=/home/ubuntu/sample-resources-0.2.0/worlds/
export CLOISIM_MODEL_PATH=/home/ubuntu/sample-resources-0.2.0/models/

**Comment by hyunseok-yang** [comment]
> Ah, I did not run CLOiSim...
> After I added another path into an environment, export CLOISIM_FILES_PATH="/home/ubuntu/sample-resources-0.2.0", I ran CLOiSim, but I could not figure it out where I have to change the path...
> Did I add a right path?
> 
> ![ros2_error_05](https://user-images.githubusercontent.com/67088693/94227496-97010f00-ff35-11ea-85f9-2ed5d5e1bc35.jpg)


If you cannot see any simulation popup window, I think your display setting is wrong.

Are you working at remote server through SSH?

**Comment by hyunseok-yang** [comment]
Please check if display setting is working properly.

Check display 
$ sudo apt-get install x11-apps 
$ xeyes


And nvidia graphic driver should be installed.

**Comment by misook3** [comment]
Yes! I will check the display setting and try the docker version of CLOiSim.
Many thanks for extra explanations.

**Comment by misook3** [comment]
You were right!
It turns out my graphic card (nvidia gtx 1070) driver is not compatible with released binary CLOiSim.
Only CLOiSim-1.1.0 is runable...
![ros2_cloisim_01](https://user-images.githubusercontent.com/67088693/94513951-f07d7c80-025a-11eb-8c40-9836081c0d48.jpg)

If I build the source code of CLOiSim-1.6.0, would it be runable on my notbook?
When I try to open the project of CLOiSim-1.6.0 in Unity Editor, what file should I choose?

Thanks

**Comment by hyunseok-yang** [comment]
It looks you are missing prerequisite library.
[Usage](https://github.com/lge-ros2/cloisim/wiki/Usage)

sudo apt-get install **libvulkan1**

Vulkan library is required since version 1.1.1.

**Comment by misook3** [comment]
I changed the graphic card to rtx 2070 and installed vulkan library.
Now it worked.
![rtx2070_vulkan_cloisim](https://user-images.githubusercontent.com/67088693/96108357-6ef34300-0f18-11eb-8453-6d4ace436984.jpg)

Many thanks.

**Comment by zikprid0** [comment]
@misook3 Good job!
